config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "home#index"
  resources :home, only: [:index, :destroy]
  resources :login, only: [:new, :create]
  resources :sign_up, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  # name validation
  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  before_save :firstname_capitalize, :lastname_capitalize

  # email validation
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  before_save :downcase_email

  #  password validation
  has_secure_password
  validates :password, length: { minimum: 6 }

  # account status (learner or teacher)
  enum status: { learn: 0, educate: 1 }
  validates :status, presence: true

  # custom validators
  def firstname_capitalize
    self.firstname = self.firstname.capitalize
  end

  def lastname_capitalize
    self.lastname = self.lastname.capitalize
  end

  def downcase_email
    self.email = self.email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :current_user

  def index
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      # create the session
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in Successfully!"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/home/index.html.erb
<%= render "shared/navbar" %>

<section>
  <div class='container-fluid bg-success-subtle' style='height: 500px'>
    <div class='row h-100'>
      <div class='col d-flex flex-column justify-content-center align-items-center gap-3 text-center p-3'>
        <h2>Welcome to your educational journey!</h2>
        <p>
          Take the opportunity to actively engage in learning by seeking out knowledge and insights from other users, who may have diverse experiences and perspectives to share. By doing so, you can broaden your understanding of various topics, gaining valuable skills and ideas that might not be accessible through traditional means. Additionally, consider contributing to the community by educating others on new career paths and opportunities. Sharing your expertise and guidance can help others navigate their professional journeys, potentially opening doors to new possibilities and fostering a collaborative environment where everyone benefits from collective growth and shared learning.
          </p>
        <%= link_to 'Get Started', new_sign_up_path, class: 'btn btn-light' %>
      </div>
      <div class='col'>

      </div>
    </div>
  </div>
</section>

<% if current_user.present? %>
  <%= link_to "Logout", home_index_path, method: :delete, class: "nav-link" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/flash" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<%= render "shared/navbar" %>

<div class="container-fluid d-flex justify-content-center align-items-center" style="margin-top: 12rem;">
  <div class="card w-50 p-2">
    <h1>Login</h1>
    <%= form_with url: login_index_path do |form| %>
      <div class="form-group mb-3">
         <%= form.label :email, class: "fw-semibold" %>
         <%= form.email_field :email, class: "form-control" %>
       </div>

        <div class="form-group mb-3">
          <%= form.label :password, class: "fw-semibold" %>
          <%= form.password_field :password, class: "form-control" %>
        </div>

        <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-fluid p-2 shadow">
  <div class="row">
    <div class="col">
      <%= link_to 'Social', root_path, class: 'nav-link fw-bold fs-2' %>
    </div>
    <div class="col d-flex justify-content-end align-items-center gap-3 fw-semi-bold fs-4">
      <%= link_to 'Sign-up', new_sign_up_path, class: 'nav-link' %>
      <%= link_to 'Login', new_login_path, class: 'nav-link' %>
    </div>
  </div>
</div>

app/views/sign_up/new.html.erb
<%= render "shared/navbar" %>

<div class="container d-flex align-items-center" style="height: 100vh;">
  <div class="container-sm w-50 border border-3 rounded p-2">
    <h1 class="text-center">Register account here</h1>
    <%= form_with(model: @user, url: sign_up_index_path, class: "form") do |form| %>

      <% if @user.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <div class="form-group mb-3">
        <%= form.label :firstname, class: "fw-semibold" %>
        <%= form.text_field :firstname, class: "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :lastname, class: "fw-semibold" %>
        <%= form.text_field :lastname, class: "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :email, class: "fw-semibold" %>
        <%= form.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :password, class: "fw-semibold" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :password_confirmation, class: "fw-semibold" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :status, class: "fw-semibold" %> </br>
        <%= form.radio_button :status, "learn" %> Learn
        <%= form.radio_button :status, "educate" %> Educate
      </div>

      <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>